# Generated by Django 6.0.4 on 2026-05-03 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('stock', models.DecimalField(decimal_places=1, max_digits=10)),
                ('unidad', models.CharField(choices=[('Kg', 'Kilogramos'), ('Lt', 'Litros'), ('Pza', 'Piezas'), ('Potes', 'Potes'), ('Bultos', 'Bultos'), ('Docenas', 'Docenas')], default='Kg', max_length=20)),
                ('stock_minimo', models.DecimalField(decimal_places=1, default=10, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='inventario/')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventario.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
