# Generated by Django 6.0.4 on 2026-05-03 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventario', '0001_initial'),
        ('Sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_inventario', to='Sucursales.sucursal', verbose_name='Sucursal'),
        ),
    ]
