# Generated by Django 6.0.4 on 2026-05-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_alter_categoria_options_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio unitario del producto', max_digits=10, verbose_name='Precio de Venta'),
        ),
    ]
