# Generated by Django 6.0.4 on 2026-05-16 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_producto_precio'),
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventario.producto', verbose_name='Producto'),
        ),
    ]
