# Generated by Django 6.0.4 on 2026-05-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_alter_detallepedido_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='iva',
        ),
    ]
