# Generated by Django 6.0.4 on 2026-05-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_remove_pedido_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('delivery', 'Delivery')], default='efectivo', max_length=20),
        ),
    ]
