# Generated by Django 6.0.4 on 2026-05-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada de Inventario'), ('retiro', 'Retiro de Caja'), ('validacion', 'Validación de Stock'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('matutino', 'Turno Matutino'), ('vespertino', 'Turno Vespertino'), ('nocturno', 'Turno Nocturno')], default='matutino', max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_cierre', models.TimeField(auto_now_add=True)),
                ('fondo_inicial', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('ventas_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ventas_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ventas_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('efectivo_real', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billetes_100', models.PositiveIntegerField(default=0)),
                ('billetes_50', models.PositiveIntegerField(default=0)),
                ('billetes_20', models.PositiveIntegerField(default=0)),
                ('billetes_10', models.PositiveIntegerField(default=0)),
                ('total_esperado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Corte de Caja',
                'verbose_name_plural': 'Cortes de Caja',
                'ordering': ['-fecha', '-hora_cierre'],
            },
        ),
    ]
