# Generated by Django 6.0.4 on 2026-05-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CierreCaja', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cierrecaja',
            name='billetes_10',
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='billetes_1000',
            field=models.PositiveIntegerField(default=0, verbose_name='Billetes $1000'),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='billetes_200',
            field=models.PositiveIntegerField(default=0, verbose_name='Billetes $200'),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='billetes_500',
            field=models.PositiveIntegerField(default=0, verbose_name='Billetes $500'),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='monedas_1',
            field=models.PositiveIntegerField(default=0, verbose_name='Monedas $1'),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='monedas_10',
            field=models.PositiveIntegerField(default=0, verbose_name='Monedas $10'),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='monedas_2',
            field=models.PositiveIntegerField(default=0, verbose_name='Monedas $2'),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='monedas_5',
            field=models.PositiveIntegerField(default=0, verbose_name='Monedas $5'),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='billetes_100',
            field=models.PositiveIntegerField(default=0, verbose_name='Billetes $100'),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='billetes_20',
            field=models.PositiveIntegerField(default=0, verbose_name='Billetes $20'),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='billetes_50',
            field=models.PositiveIntegerField(default=0, verbose_name='Billetes $50'),
        ),
    ]
