# Generated by Django 6.0.4 on 2026-05-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CierreCaja', '0003_remove_cierrecaja_billetes_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrecaja',
            name='turno',
            field=models.CharField(choices=[('matutino', 'Turno Matutino'), ('vespertino', 'Turno Vespertino')], default='matutino', max_length=20),
        ),
    ]
