# Generated by Django 6.0.4 on 2026-05-25 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CierreCaja', '0004_alter_cierrecaja_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cierrecaja',
            name='billetes_100',
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='billetes_1000',
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='billetes_20',
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='billetes_200',
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='billetes_50',
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='billetes_500',
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='diferencia',
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='fondo_inicial',
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='monedas_1',
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='monedas_10',
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='monedas_2',
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='monedas_5',
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='total_esperado',
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='ventas_delivery',
        ),
    ]
