# Generated by Django 6.0.4 on 2026-05-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de Perfil'),
        ),
    ]
