# Generated by Django 6.0.4 on 2026-05-19 03:10

import Sucursales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursales', '0002_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=Sucursales.models.usuario_foto_path, verbose_name='Foto de Perfil'),
        ),
    ]
