# Generated by Django 6.0.4 on 2026-05-03 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=200, verbose_name='Producto')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(default='KG', max_length=20)),
                ('fecha_entrada', models.DateField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Entrada de Insumo',
                'verbose_name_plural': 'Entradas de Insumos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
