# Generated by Django 6.0.4 on 2026-05-03 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntradaMercancia', '0001_initial'),
        ('Sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradainsumo',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_mercancia', to='Sucursales.sucursal', verbose_name='Sucursal de Destino'),
        ),
    ]
