# Generated by Django 6.0.4 on 2026-05-14 16:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntradaMercancia', '0002_initial'),
        ('Sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradainsumo',
            name='categoria',
            field=models.CharField(choices=[('pollo', 'Pollo/Partes de pollo'),  ('acompañamientos', 'Acompañamientos')], default='pollo', help_text='Categoría del producto para clasificación', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='entradainsumo',
            name='sincronizado',
            field=models.BooleanField(default=False, verbose_name='Sincronizado con Inventario'),
        ),
        migrations.AlterField(
            model_name='entradainsumo',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='entradainsumo',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='entradainsumo',
            name='fecha_entrada',
            field=models.DateField(verbose_name='Fecha de Entrada'),
        ),
        migrations.AlterField(
            model_name='entradainsumo',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Adicionales'),
        ),
        migrations.AlterField(
            model_name='entradainsumo',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_mercancia', to='Sucursales.sucursal', verbose_name='Sucursal de Destino'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradainsumo',
            name='unidad',
            field=models.CharField(default='KG', max_length=20, verbose_name='Unidad de Medida'),
        ),
    ]
