# Generated by Django 6.0.4 on 2026-05-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntradaMercancia', '0003_entradainsumo_categoria_entradainsumo_sincronizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradainsumo',
            name='producto',
            field=models.CharField(choices=[('Pollo', 'Pollo'), ('Cabeza', 'Cabeza'), ('Patita', 'Patita'), ('Alitas', 'Alitas'), ('Salchica', 'Salchica'), ('Tacos', 'Tacos'), ('Arroz', 'Arroz'), ('Chiltepin', 'Chiltepin'), ('Salsas', 'Salsas'), ('Chile en polvo sasonador', 'Chile en polvo sasonador'), ('Chile en polvo', 'Chile en polvo'), ('Condimento', 'Condimento')], default='Pollo', max_length=200, verbose_name='Producto'),
        ),
    ]
