# Generated by Django 6.0.4 on 2026-05-03 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('matutino', 'Turno Matutino'), ('vespertino', 'Turno Vespertino'), ('nocturno', 'Turno Nocturno')], max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total')),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Diferencia')),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Insumo')),
                ('unidad', models.CharField(default='kg', max_length=30, verbose_name='Unidad')),
                ('stock_esperado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Teórico')),
                ('stock_fisico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Real')),
                ('costo_diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Estimado')),
                ('icono', models.CharField(default='inventory_2', max_length=50, verbose_name='Ícono Material')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='MetaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo_monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Objetivo ($)')),
                ('fecha_inicio', models.DateField(verbose_name='Inicio de Semana')),
            ],
            options={
                'verbose_name': 'Meta Semanal',
                'verbose_name_plural': 'Metas Semanales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
    ]
