# Generated by Django 6.0.4 on 2026-05-19 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reportes', '0002_initial'),
        ('Sucursales', '0003_alter_usuario_foto_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrecaja',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sucursales.sucursal'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sucursales.sucursal'),
        ),
        migrations.AlterField(
            model_name='metasemanal',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sucursales.sucursal'),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_caja', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
