# Generated by Django 6.0.4 on 2026-05-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('descanso', 'En Descanso'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('en_turno', models.BooleanField(default=False, verbose_name='En turno activo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='personal/')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='RolPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Rol')),
                ('minimo_turno', models.PositiveIntegerField(default=1, verbose_name='Mínimo por turno')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Descripción')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
    ]
