# Generated by Django 6.0.4 on 2026-05-03 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('empleado', 'Empleado')], default='empleado', max_length=20, verbose_name='Rol'),
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_alta',
        ),
        migrations.AddField(
            model_name='empleado',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RolPersonal',
        ),
    ]
