# Generated by Django 6.0.4 on 2026-05-12 07:04

import Personal.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0003_alter_empleado_rol_remove_empleado_fecha_alta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('hora_entrada', models.TimeField(blank=True, null=True, verbose_name='Hora de Entrada')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('tardanza', 'Tardanza'), ('descanso', 'Día de Descanso'), ('vacaciones', 'Vacaciones')], default='ausente', max_length=20)),
                ('es_dia_descanso', models.BooleanField(default=False, verbose_name='Día de Descanso')),
                ('justificante', models.FileField(blank=True, null=True, upload_to=Personal.models.ruta_justificante, verbose_name='Justificante de Ausencia')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='Personal.empleado')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha', 'empleado__usuario__first_name'],
                'unique_together': {('empleado', 'fecha')},
            },
        ),
    ]
