# Generated by Django 6.0.4 on 2026-05-13 06:39

import Personal.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0004_asistencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='justificante',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asistencia',
            name='dia_descanso_semanal',
            field=models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True, verbose_name='Día de Descanso Semanal'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='registro_automatico',
            field=models.BooleanField(default=False, verbose_name='Registro Automático'),
        ),
        migrations.CreateModel(
            name='Justificante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Ausencia')),
                ('motivo', models.CharField(choices=[('enfermedad', 'Enfermedad'), ('personal', 'Asunto Personal'), ('familiar', 'Asunto Familiar'), ('medico', 'Cita Médica'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Motivo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('archivo', models.FileField(help_text='PDF, imagen o documento que respalde el justificante', upload_to=Personal.models.ruta_justificante, verbose_name='Archivo Adjunto')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('comentario_revision', models.TextField(blank=True, verbose_name='Comentario de Revisión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('asistencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='justificantes', to='Personal.asistencia')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificantes', to='Personal.empleado')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificantes_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Revisado Por')),
            ],
            options={
                'verbose_name': 'Justificante',
                'verbose_name_plural': 'Justificantes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
