# Generated by Django 6.0.4 on 2026-05-18 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0005_remove_asistencia_justificante_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='personal',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='turno',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turno',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='Personal.empleado'),
        ),
        migrations.AddField(
            model_name='turno',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='tipo_turno',
            field=models.CharField(choices=[('matutino', 'Matutino (8:00 - 16:00)'), ('vespertino', 'Vespertino (16:00 - 00:00)'), ('nocturno', 'Nocturno (00:00 - 8:00)'), ('completo', 'Turno Completo')], default='completo', max_length=20),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(verbose_name='Fecha del Turno'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora_fin',
            field=models.TimeField(verbose_name='Hora de Fin'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora de Inicio'),
        ),
    ]
