# Generated by Django 6.0.4 on 2026-05-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0006_remove_turno_nombre_remove_turno_personal_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('empleado', 'fecha')},
        ),
    ]
