# Generated by Django 6.0.4 on 2026-05-18 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0007_alter_turno_unique_together'),
        ('Sucursales', '0002_usuario_foto_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sucursales.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turno',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas o Instrucciones'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='tipo_turno',
            field=models.CharField(choices=[('matutino', 'Matutino (8:00 - 16:00)'), ('vespertino', 'Vespertino (16:00 - 00:00)'), ('completo', 'Turno Completo (8:00 - 22:00)'), ('medio_tiempo', 'Medio Tiempo'), ('personalizado', 'Personalizado')], default='completo', max_length=20),
        ),
    ]
