# Generated by Django 6.0.4 on 2026-05-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0008_turno_sucursal_alter_turno_creado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='dia_descanso_semanal',
        ),
        migrations.AddField(
            model_name='empleado',
            name='dia_descanso_semanal',
            field=models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True, verbose_name='Día de Descanso Semanal'),
        ),
    ]
