# Generated by Django 6.0.4 on 2026-05-19 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0009_remove_asistencia_dia_descanso_semanal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos_programados', to='Personal.empleado'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='tipo_turno',
            field=models.CharField(choices=[('matutino', 'Matutino (8:00 - 13:00)'), ('vespertino', 'Vespertino (13:00 - 20:00)'), ('medio_tiempo', 'Medio Tiempo (Personalizado)')], default='matutino', max_length=20),
        ),
    ]
